# Name of the workflow
name: First Workflow
# Whem this workflow is executed, event or events
on: workflow_dispatch # Manually start the workflow
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo !Gone - bye!"
        
